### ISSUE TITLE
Compressed images

### ISSUE THREAD

**Issue by Faalagorn** [frostworx/repo-assets#1]
Since I can't replace GitHub images from the GUI, I'd have to fork the repo locally to upload new version of images, but here's the two compressed PNG files in case you want it, I used this [zopflipng fork from MrKrzYch00](https://github.com/MrKrzYch00/zopfli) with these options: `--iterations=1000000 --mui=10000 --all --lossy_transparent --lossy_8bit --alpha_cleaners=bhvapw`.

For 64 pixel logo it's:  Input size: 863 (0K) Result size: 852 (0K). Percentage of original: 98.725% 
![steamtinkerlaunch-logo_64px](https://user-images.githubusercontent.com/4951331/119242060-3a550300-bb5b-11eb-9a58-199e4d1fff63.png)
For 256 pixel logo it's: Input size: 3562 (3K) Result size: 3358 (3K). Percentage of original: 94.273%
![steamtinkerlaunch-logo_256px](https://user-images.githubusercontent.com/4951331/119252713-f6d7b480-bbad-11eb-9ff8-f5f63d64f3b8.png)

Feel free to replace them for a little faster loading times/less disk space being used. :)

These options are over the top and some speed saving and possibly some lower sizes could probably be used by more clever filters/options being used and I didn't touch the JPGs and GIFs in here but these can be compressed (losslessly) as well. Alternatively, some newer formats could be used for more savings, such as webp.

**Comment by frostworx** [comment]
Thanks for the suggestion. The pngs are not used in stl itself though.
The base64 encoded string for the scaled down 64pixel picture in genDefIcon becomes bigger than the current one.
Might be worth a try to scale down the jpegs with guetzli, but as you do not load all the pictures at once when reading the wiki
and it might also lead to compatibility problems I do not plan to do it for now.

**Comment by Pokefinder-org** [comment]
Sorry to hijack this issue to msg to frostworx :) Pls delete
Bin grad am ydkj fummeln, wie du vor längerer Zeit - pls mailto count0@pokefinder.org - danke! (doofes hub hier hat echt keine msgs - pfff)

**Comment by frostworx** [comment]
Hi @Pokefinder-org
totally forgot your message here until I now
but I just received an email because of your comment [here](https://github.com/Mwyann/ydkjs/issues/1#issuecomment-1086816797)
I'm afraid though I can't help you any further, as I haven't touched the ydkjs project since my last comment above yours :)

No idea if this is interesting for you, but there are several hacks/mods, which allow you to play the classic German YDKJ 1-4 on modern systems _(f.e. they work excellent on my linux system, where I start them instead of the english versions by overriding the game exe)_. If you're interested, I try to find the source thread _(on steam)_
